
# Classification

### Demo 1 - Logistic Regression in Python

In this demo, you will apply logistic regression algorithm using scikit-learn library.

---

## Problem Statement

The dataset contain details of users like User ID, Gender, Age, EstimatedSalary and Purchased. The data shows whether a person is likely to purchase the artefacts advertised or not. Based on the data we have to generate a model that can predict whether the person will make a purchase or not.

---

## Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn import metrics

## Dataset

In [3]:
ad_data=pd.read_csv('Social_Network_Ads.csv')
ad_data.head()
ad_data.shape

(400, 5)

## Data Analysis

In [4]:
#Checking for any null values
ad_data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
#Label encoding
lbl=LabelEncoder()
ad_data['Gender']=lbl.fit_transform(ad_data['Gender'])
print(ad_data)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]


<div style="background-color:##FBFFE3">
    <div style="float:left">
        <img src='https://drive.google.com/uc?export=download&id=1gpc8kbwaenTpaIvnO_MQR3vw12rKYQrJ', width=20,height=20,>
    </div>
    <span style="padding:20px;">
    Dataset does not contain any null values means it is not required to replace/remove data.
    </span>
</div>

In [6]:
#Splitting dataset into dependent and independent variables
#Eliminating User ID and Gender as they would not have any impact
X=ad_data[['Age','EstimatedSalary']]
y=ad_data['Purchased']

In [ ]:
ad_data.info()

<div style="background-color:##EDF9FF">
  <ul><li><h3>Feature Scaling</h3></li></ul>
</div>

In [ ]:
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

<div style="background-color:##FBFFE3">
    <div style="float:left">
        <img src='https://drive.google.com/uc?export=download&id=1gpc8kbwaenTpaIvnO_MQR3vw12rKYQrJ', width=20,height=20,>
    </div>
    <span style="padding:20px;">
    Using this as there is wide gap between Age and EstimatedSalary and standardizing datasets ensures model is generated properly. The mean should be near to 0 and standard deviation should be near 1 before training the model which is ensured by this
    </span>
</div>

<div style="background-color:##EDF9FF">
  <ul><li><h3>
      Training And Testing Set
      </h3></li></ul>
</div>

In [8]:
#Splitting dataset into training and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)
print(X_train.shape,X_test.shape)
print(y_train.shape,y_test.shape)

(300, 2) (100, 2)
(300,) (100,)


## Logistic Regression Training

Some important hyperparameters that should be considered before training the model:
- __C__: Inverse of regularization strength. Should be float and smaller values specify strong regularization strength.
- __solver__: Algorithm to optimise the problem.Like _'liblinear'_ is used for small datasets while _'sag'_ or _'saga'_ handle large datasets easily
- __multi_class__: To specify either the problem is binary or multiclass. _'ovr'_ is used to specify a binary problem while _'multinominal'_ for a multiclass problem. _'auto'_ selects automatically.

For further information about other parameter you can refer to:
<a href='https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression'>Logistisc Regression scikit-learn</a> 

In [ ]:
lr_ad=LogisticRegression()
lr_ad.fit(X_train,y_train)

## Visualising Logistic Regression

In [ ]:
def plot(X,y,mset):
    p=['Not Purchased','Purchased']
    X1, X2 = np.meshgrid(np.arange(start = X[:, 0].min() - 1, stop = X[:, 0].max() + 1,   step = 0.01),
                         np.arange(start = X[:, 1].min() - 1, stop = X[:, 1].max() + 1, step = 0.01))

    #To plot boundaries
    #In general, the space is divided into decision boundaries
    plt.figure(figsize=(8,6))
    plt.contourf(X1, X2, lr_ad.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
                 alpha = 0.75, cmap = ListedColormap(('#F1674F', '#BEDDB7')))

    plt.xlim(X1.min(), X1.max())
    plt.ylim(X2.min(), X2.max())

    for i, j in enumerate(set(y)):
        plt.scatter(X[y == j, 0], X[y == j, 1],
                    c = ['#F84C51', '#23807A'][i], label = p[j])
    plt.title('Logistic Regression ('+mset+')')
    plt.xlabel('Age')
    plt.ylabel('Estimated Salary')
    plt.legend()
    return plt

<div style="background-color:##EDF9FF">
  <ul><li><h3>Training Set</h3></li></ul>
</div>

In [ ]:
y_pred=lr_ad.predict(X_train)
print(y_pred)
#plt.show(plot(X_train,y_pred,'Training Set'))

In [ ]:
print('Accuracy: ',accuracy_score(y_train,y_pred))

In [ ]:
new_pred=lr_ad.predict([[40,20000]])
print(new_pred)

<div style="background-color:##EDF9FF">
  <ul><li><h3>Test Set</h3></li></ul>
</div>

In [ ]:
y_pred=lr_ad.predict(X_test)
print(y_pred)
#plt.show(plot(X_test,y_pred,'Testing Set'))

---

## Accuracy Score

In [ ]:
print('Accuracy: ',accuracy_score(y_test,y_pred))

## Decision Boundary

- Decision boundaries are defined by the threshold value
- Model coefficients define location and orientation of decision boundary
- Since data has two features then boundary hypothesis would be:

    # \begin{equation*}h_{\theta}=g({\theta}_{0}+{\theta}_{1}x_{1}+{\theta}_{2}x_{2})={\theta}^{T}x \end{equation*} 

In [ ]:
#For theta_0:
print(lr_ad.intercept_ )
#For theta_1 and theta_2:
print(lr_ad.coef_ )

---

# Multinominal Logistic Regression

Dataset includes three iris species with 50 samples each and some properties about each flower. 
The columns in this dataset are:

- __Id__: SPL-SPW-PTL-PTW(CM)
- __SepalLengthCm__: Length of the sepal (in cm)
- __SepalWidthCm__: Width of the sepal (in cm)
- __PetalLengthCm__: Length of the petal (in cm)
- __PetalWidthCm__: Width of the petal (in cm)
- __Species__: Species name


## Importing Dataset

In [2]:
#Importing the dataset using pandas
iris_data=pd.read_csv('Iris.csv')
iris_data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Data Analysis

In [3]:
#Dataset shape to get number of rows and columns
iris_data.shape

(150, 6)

<div style="background-color:##EDF9FF">
  <ul><li><h3>Checking Datatypes</h3></li></ul>
</div>

In [4]:
iris_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


<div style="background-color:##EDF9FF">
  <ul><li><h3>Checking Null Values</h3></li></ul>
</div>

In [5]:
#Checking for null values
iris_data.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

<div style="background-color:##FBFFE3">
    <div style="float:left">
        <img src='https://drive.google.com/uc?export=download&id=1gpc8kbwaenTpaIvnO_MQR3vw12rKYQrJ', width=20,height=20,>
    </div>
    <span style="padding:20px;">
    None of the columns contain null values so there is no need to remove/replace data
    </span>
</div>

<div style="background-color:##EDF9FF">
  <ul><li><h3>Labelencoding Target Variable</h3></li></ul>
</div>

In [7]:
#Using labelencoder to encode the target variable
lb=LabelEncoder()
#lb.fit(iris_data['Species'])
iris_data['Species']=lb.fit_transform(iris_data['Species'])
print(iris_data['Species'])

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64


<div style="background-color:##EDF9FF">
  <ul><li><h3>Dividing Feature And Target</h3></li></ul>
</div>

In [8]:
#Divide the dataset into independent and dependent variables
X=iris_data[['SepalWidthCm','PetalWidthCm']]
y=iris_data.Species

In [10]:
print(X.describe())

       SepalWidthCm  PetalWidthCm
count    150.000000    150.000000
mean       3.054000      1.198667
std        0.433594      0.763161
min        2.000000      0.100000
25%        2.800000      0.300000
50%        3.000000      1.300000
75%        3.300000      1.800000
max        4.400000      2.500000


<div style="background-color:##EDF9FF">
  <ul><li><h3>Feature Scaling</h3></li></ul>
</div>

In [12]:
#Feature Scaling
sc = StandardScaler()
X = sc.fit_transform(X)
print(X)

[[ 1.03205722e+00 -1.31297673e+00]
 [-1.24957601e-01 -1.31297673e+00]
 [ 3.37848329e-01 -1.31297673e+00]
 [ 1.06445364e-01 -1.31297673e+00]
 [ 1.26346019e+00 -1.31297673e+00]
 [ 1.95766909e+00 -1.05003079e+00]
 [ 8.00654259e-01 -1.18150376e+00]
 [ 8.00654259e-01 -1.31297673e+00]
 [-3.56360566e-01 -1.31297673e+00]
 [ 1.06445364e-01 -1.44444970e+00]
 [ 1.49486315e+00 -1.31297673e+00]
 [ 8.00654259e-01 -1.31297673e+00]
 [-1.24957601e-01 -1.44444970e+00]
 [-1.24957601e-01 -1.44444970e+00]
 [ 2.18907205e+00 -1.31297673e+00]
 [ 3.11468391e+00 -1.05003079e+00]
 [ 1.95766909e+00 -1.05003079e+00]
 [ 1.03205722e+00 -1.18150376e+00]
 [ 1.72626612e+00 -1.18150376e+00]
 [ 1.72626612e+00 -1.18150376e+00]
 [ 8.00654259e-01 -1.31297673e+00]
 [ 1.49486315e+00 -1.05003079e+00]
 [ 1.26346019e+00 -1.31297673e+00]
 [ 5.69251294e-01 -9.18557817e-01]
 [ 8.00654259e-01 -1.31297673e+00]
 [-1.24957601e-01 -1.31297673e+00]
 [ 8.00654259e-01 -1.05003079e+00]
 [ 1.03205722e+00 -1.31297673e+00]
 [ 8.00654259e-01 -1

<div style="background-color:##EDF9FF">
  <ul><li><h3>Traing And Testing Set</h3></li></ul>
</div>

In [13]:
#Split the data into training and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,
                                               random_state=5) #20 percent of data will be used for testing purpose

## Logistic Regression Training

In [14]:
#Fitting the model
mlr=LogisticRegression(C=1,solver='lbfgs', multi_class='multinomial')
mlr.fit(X_train,y_train)

LogisticRegression(C=1, multi_class='multinomial')

---

## Visualising The Model

In [ ]:
def plot_multi(X,y,mset):
    p=lb.classes_
    X1, X2 = np.meshgrid(np.arange(start = X[:, 0].min() - 1, stop = X[:, 0].max() + 1,   step = 0.01),
                         np.arange(start = X[:, 1].min() - 1, stop = X[:, 1].max() + 1, step = 0.01))

    #To plot boundaries
    #In general, the space is divided into decision boundaries
    plt.figure(figsize=(8,6))
    plt.contourf(X1, X2, mlr.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
                 alpha = 0.75, cmap = ListedColormap(('#F74E69', '#BDF54E','#72ADDA')))

    plt.xlim(X1.min(), X1.max())
    plt.ylim(X2.min(), X2.max())

    for i, j in enumerate(set(y)):
        plt.scatter(X[y == j, 0], X[y == j, 1],
                    c = ['#BE001E', '#7DBB00','#074C81'][i], label = p[j])
    plt.title('Logistic Regression ('+mset+')')
    plt.xlabel('Sepal Width')
    plt.ylabel('Petal Width')
    plt.legend()
    return plt

<div style="background-color:##EDF9FF">
  <ul><li><h3>Training Set</h3></li></ul>
</div>

In [21]:
y_mlr=mlr.predict(X_train)
print(y_mlr)
#plt.show(plot_multi(X_train,y_mlr,'Training Set'))

[2 1 0 2 2 1 0 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 2 1 2 2 1 2 1 0 2 1 1 1 1
 2 0 0 2 1 0 0 1 0 2 1 0 1 2 1 0 2 2 2 2 0 0 2 2 1 2 0 2 2 0 0 1 0 0 0 1 2
 2 0 0 0 1 1 0 0 1 0 2 1 2 1 0 2 0 2 0 0 2 0 2 1 1 1 2 2 1 2 0 1 2 2 0 1 1
 2 1 0 0 0 2 1 2 0]


In [22]:
#Training Accuracy
print('Accuracy: ',accuracy_score(y_train,y_mlr))

Accuracy:  0.95


<div style="background-color:##EDF9FF">
  <ul><li><h3>Test Set</h3></li></ul>
</div>

In [23]:
y_mlr=mlr.predict(X_test)
print(y_mlr)
#plt.show(plot_multi(X_test,y_mlr,'Test Set'))

[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


## Accuracy Score

In [24]:
mlr_pred=mlr.predict(X_test)
print('Accuracy: ',accuracy_score(y_test,mlr_pred))

Accuracy:  0.9666666666666667


In [25]:
mlr.predict([[3.5,0.2]]) #User data

array([0], dtype=int64)

<b><i>Conclusion</i></b>: In this demonstration, we have gained an understanding of how to apply logistic regression algorithm.