In [1]:
#Create numpy array
import numpy as np

In [5]:
#arr=np.array([34,56,78,90,23])
arr=np.array([34,56,78,90,23])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
<U11


In [11]:
#Arange Function 
arr=np.arange(10,20)  #start,stop,step
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [9]:
lst=list(range(10,50))
print(lst)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [20]:
#Ones and zero
arr=np.ones(5) #Default data type is float
print(arr)
arr=np.zeros(5)
print(arr)
arr=np.ones(5,dtype='int')
print(arr)
print("No of Dimentions:",arr.ndim)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[1 1 1 1 1]
No of Dimentions: 1


In [23]:
#2D Array
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print("No of Dimentions(axes):",arr.ndim)
print("Shape:",arr.shape)
print("No of elements(size):",arr.size)
print("Bytes:",arr.itemsize)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
No of Dimentions(axes): 2
Shape: (3, 3)
No of elements(size): 9
Bytes: 4


In [30]:
#Random Array
arr=np.random.rand(3,4)
print(arr*100)

[[69.58081662 95.68021114 42.5908064  45.19863306]
 [56.10058339 35.39489923 57.7265116   0.8188289 ]
 [24.31517966 11.83855516 14.63966201 82.47878407]]


In [37]:
#Array multiplication
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[10,11],[20,21],[30,31]])
print(arr1)
print(arr2)
arr=np.dot(arr1,arr2)
print(arr)

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]
[[140 146]
 [320 335]]


In [35]:
arr=arr1+arr2
print(arr)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [47]:
#Read(import) data   file--->nparray
marks=np.loadtxt('C:\\Study\\Edureka Notebooks\\Module 05 Numpy\\marks.csv',delimiter=',',usecols=(5),skiprows=1,dtype='int')
print(marks)

[420 280 350 269 317 470 333 365 305 350 460 474 409 377 415 382 298 462
 370 313 464 302 252 259 308 392 424 403 370 328 398 434 291 472 263 439
 464 449 401 364 296 292 438 357 331 317 429 407 321 274 447 274 437 411
 257 310 396 270 311 459 378 316 283 266 381 409 313 306 448 348 292 400
 352 441 428 309 441 439 264 281 302 432 423 336 383 321 469 270 341 281
 403 333 323 348 345 397 449 261 456 370 322 379 446 404 301 254 351 444
 264 286 463 273 316 324 465 398 324 340 414 346 408 332 394 474 398 262
 410 391 444 461]


In [45]:
#Aggregate functions in  numpy
print("Sum:",marks.sum())
print(f"Max marks:{marks.max()},Min marks:{marks.min()}")
print("Average Marks:",round(marks.mean(),2))
print("Standard Deviation:",marks.std())
print("Variance:",marks.var())

Sum: 47356
Max marks:474,Min marks:252
Average Marks: 364.28
Standard Deviation: 66.17947803971762
Variance: 4379.723313609467


In [53]:
#Reshaping of array
import numpy as np
arr=np.array([45,26,35,89,10,87]) #1D
print(arr.shape)
arr_new=arr.reshape(2,3)
#arr_new=arr.reshape(3,3) can not reshape
print(arr_new)

(6,)
[[45 26 35]
 [89 10 87]]


In [56]:
#Transpose
print(arr_new)
print(arr_new.shape)
arr=arr_new.transpose()
print(arr)

[[45 26 35]
 [89 10 87]]
(2, 3)
[[45 89]
 [26 10]
 [35 87]]


In [62]:
#Flattening
print(arr)
arr_new=arr.flatten()
arr_new=arr.reshape(1,-1)
arr_new=arr.ravel()
print(arr_new)

[[45 89]
 [26 10]
 [35 87]]
[45 89 26 10 35 87]


In [94]:
#Slicing
#1D
arr=np.array([34,26,78,98,67,45,37,90,40,29])
print(arr[5])
print(arr[5:10]) #start:stop:step
print(arr[::2])
arr[0]=100
print(arr)

45
[45 37 90 40 29]
[34 78 67 37 40]
[100  26  78  98  67  45  37  90  40  29]


In [71]:
#2D Slicing
arr=np.array([[34,26,78],[98,67,45],[37,90,40]])
print(arr)
print(arr[0:2,1:3])
print(arr[1:3,0:2])

[[34 26 78]
 [98 67 45]
 [37 90 40]]
[[26 78]
 [67 45]]
[[98 67]
 [37 90]]


In [76]:
#join arrays(stacking)
arr1=np.array([34,26,78,98,67])
arr2=np.array([45,37,90,40,29]) 
arr=np.vstack([arr1,arr2])#Verticcal Stacking
arr=np.hstack([arr1,arr2])#Horizontal Stacking
print(arr)

[34 26 78 98 67 45 37 90 40 29]


In [78]:
#2D stacking
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[50,60],[70,80]])
arr=np.vstack([arr1,arr2])
arr=np.hstack([arr1,arr2]) #Concatination
print(arr)

[[10 20 50 60]
 [30 40 70 80]]


In [83]:
#Fancy Indexing
arr=np.array([34,26,78,98,67,45,37,90,40,29])
print(arr[6]) #Normal Indexing
ind=np.array([[3,4,2],[5,6,9]])
print(arr[ind])

37
[[98 67 78]
 [45 37 29]]


In [89]:
#Broadcasting Operations
lst=[10,20,30]
print(lst*5)
arr=np.array(lst)
print(arr*5)
print(arr+60)
arr=np.array([[3,4,2],[5,6,9]])
print(arr*3)

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]
[ 50 100 150]
[70 80 90]
[[ 9 12  6]
 [15 18 27]]


In [90]:
#Iterate through arrays
arr=np.array([[34,26,78],[98,67,45],[37,90,40]])
for r in arr:
    print(r)

[34 26 78]
[98 67 45]
[37 90 40]


In [92]:
for x in np.nditer(arr):#go element wise
    if x%2==0:
        print(x)

34
26
78
98
90
40


In [93]:
arr=np.array([[34,26,78],[98,67,45],[37,90,40]])
print(np.split(arr,3))

[array([[34, 26, 78]]), array([[98, 67, 45]]), array([[37, 90, 40]])]
